config/routes.rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  # アドレス帳用ルーティング
  patch '/end_user' => 'end_users#update'

  resources :addresses, only: [:index, :create, :edit, :update, :destroy]
  # カートアイテム用index
  # get '/cart_items' => 'cart_items#index'
  # カートアイテム用ルーティング
  resources :cart_items, only: [:index, :create, :update, :destroy]
  # カートアイテム全削除用
  delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
  # エンドユーザログイン管理ルーティング
  devise_for :end_users
  # エンドユーザ用ルーティング
  resource :end_users, only: [:show, :update]
  get '/end_users/editing' => 'end_users#edit'
  # 退会確認ページ用
  get '/end_users/withdraw' => 'end_users#withdraw'
  # アバウトページ用
  get '/homes/about' => 'homes#about'
  # トップページ用
  root to: 'homes#top'
  # 商品用ルーティング
  resources :items, only: [:index, :show]
  # 注文用ルーティング
  resources :orders, only: [:new, :create, :index, :show]
  # 購入確認ページ用
  get '/orders/confirm' => 'orders#confirm'
  # 購入完了ページ用
  get '/orders/thanks' => 'orders#thanks'
  ##エンドユーザ用ルーティング############################################
  resource :end_users, only: [:show, :edit, :update]

  ##管理ユーザ用ルーティング#############################################
  # 管理ユーザユーザログイン管理ルーティング
  devise_for :admin_users
  namespace :admin do
    # エンドユーザ用ルーティング
    resources :end_users, only: [:index, :show, :edit, :update]
    # ジャンル用ルーティング
    resources :genres, except: [:new, :show]
    # 商品用ルーティング
    resources :items, except: [:destroy]
    # 注文用ルーティング
    resources :orders, only: [:index, :show]
    # 注文ステータス更新用ルーティング
    patch '/orders/:id' => 'orders#update_order_status'
    # 製作ステータス更新用ルーティング
    put '/orders/:id' => 'orders#update_making_status'
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
def top
  # ジャンル表示OKのやつを全部取得
  @genres = Genre.where( is_displayed: true)
  # ジャンル表示OKのやつのidを配列に変換
  genres = @genres.map{ | g | g.id }
  # ジャンル表示OKの商品を全部取得
  items = Item.where( genre_id: genres)
  # ページネーション処理
  @pages = items.page(params[:page]).reverse_order
  # 総商品数カウント（表示可能商品のみ）
  @counts = items.count
end

def home
end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/_orders_index_today.html.erb
<% t = Time.zone.now.to_date %>
<% orders = Order.where( ' created_at > ? ', t  ).where.not( ' created_at > ? ', ( t + 1.day ) ) %>
  <div class="col-xs-offset-2 col-xs-10 col-xs-offset-2">

	<h2><%= "本日の注文件数 #{orders.count}件" %></h2>
	<table>
		<tr>
			<th>購入日時</th>
			<th>購入者</th>
			<th>注文個数</th>
			<th>注文ステータス</th>
		</tr>
		<% orders.each do | order | %>
		<tr>
			<td><%= link_to order_datetime_format( order.created_at ), admin_order_path( order ) %></td>
			<td><%= order.end_user.last_name + order.end_user.first_name %></td>
			<td><%= order.order_details.map{ | order_detail | order_detail.amount }.sum %></td>
			<td><%= order.order_status %></td>
		</tr>
		<% end %>
	</table>
</div>

app/views/homes/_subtop.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-1"><%= 'ここは余白' * 20 %></div>

    <div class="col-lg-10">
      <h1>Top画面</h1>
      <% t = Time.zone.now %>
      <%= t>(t+0.day).to_date %>

      <h1>デバッグページとして使用</h1>
      <table>
        <tr>
          <th>code</th>
          <th>出力 </th>
          <th>クラス</th>
          <th>.to_date</th>
        </tr>
        <tr>
          <td>Time.zone.now</td>
          <td><%= t %></td>
          <td><%= t.class %></td>
          <td><%= t.to_date %></td>
        </tr>
        <tr>
          <td>EndUser.first.created_at</td>
          <td><%= EndUser.first.created_at %></td>
          <td><%= EndUser.first.created_at.class %></td>
          <td><%= EndUser.first.created_at.to_date %></td>
        </tr>
        <% t = t.to_datetime %>
        <tr>
          <td>各時間抽出</td>
          <td><%= t.hour %></td>
          <td><%= t.minute %></td>
          <td><%= t.sec %></td>
        </tr>
      </table>
    </div>

    <div class="col-lg-1"><%= 'ここは余白' * 20 %></div>
  </div>


  <div class="row">
    <div class="col-lg-1"><%= 'ここは余白' * 20 %></div>

    <div class="col-lg-5">
      <h2>一般ユーザ</h2>
      <% if end_user_signed_in? then %>
      現在、<span style="color:red; background-color:yellow;"><%= current_end_user.last_name%> <%= current_end_user.first_name%></span>さんがログイン中<br>
      current_end_user.is_deleted => <%= current_end_user.is_deleted.inspect%><br>
      EndUser<%= link_to 'ログアウト',  destroy_end_user_session_path, method: :delete %>
      <% else %>
      EndUserで<%= link_to 'ログイン', new_end_user_session_path %>
      <% end %><br>
      <% if end_user_signed_in? then %>
      <%= link_to 'Addresses#index => 住所録一覧', addresses_path %><br>
      <%= link_to 'Orders#index => 注文履歴一覧', orders_path %><br>
      <%= link_to 'CartItems#index => カート内アイテム一覧', cart_items_path %><br>
      <%= link_to 'CartItems#index => マイページ', end_users_path %><br>
      <% end %>
      商品登録件数（全<%= Item.count %>件）<br>
      <%= link_to 'Items#index => 商品一覧', items_path %><br>
      Items#show => 商品詳細ページ
      <% Item.all.each do |item| %><%= link_to ( " %02d" % item.id ), item_path(item.id) %><% end %>
    </div>

    <div class="col-lg-5">
      <h2>管理人</h2>
      <% if admin_user_signed_in? then %>
      AdminUser<%= link_to 'ログアウト',  destroy_admin_user_session_path, method: :delete %><br>
      <% else %>
      AdminUserで<%= link_to 'ログイン', new_admin_user_session_path %><br>
      <% end %>
      <%= link_to 'admin/Items#index => 商品一覧', admin_items_path %><br>
      <%= link_to 'admin/Items#new => 商品の新規投稿', new_admin_item_path %><br>
      <%= link_to 'admin/Orders#index => 注文履歴一覧（全部）', admin_orders_path %><br>
      <%=link_to 'admin/EndUsers#index => エンドユーザ一覧', admin_end_users_path %><br>
      アカウント登録数（全<%= EndUser.count %>ユーザ）<br>
      admin/EndUsers#show => 会員詳細ページ
      <% EndUser.all.each do |end_user| %><%= link_to ( " %02d" % end_user.id ), admin_end_user_path(end_user.id) %><% end %>
    </div>

    <div class="col-lg-1"><%= 'ここは余白' * 20 %></div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="container about">
    <%= image_tag 'cake_ya_building.png' %><br />
	<p>長野県の小さな洋菓子店「ながのCAKE」通販サイトです。</p>
	<p>県がほこる豊かな土地に育まれた味を、ご自宅で手軽にお楽しみいただけます。</p>
</div>

app/views/homes/top.html.erb
<div class="container">
	<% if not admin_user_signed_in? then %>

	<div class="row">
		<div  class="col-xs-1">
			<div id='genresShowing'>
				<button type="button" name="button" class='btn btn-primary'>ジャンル検索</button>
			</div>
			<div id="genre-window1">

				<%= render 'items/template_genres', genres: @genres %>
			</div>
		</div>

		<div class="col-xs-11">
			<%= render 'items/template_items', pages: @pages, counts: @counts, info: '商品' %>
		</div>
	<% else %>
	<%= render 'homes/orders_index_today' %>
	<% end %>
</div>
</div>

<script>
	$(function(){
		$('#genre-window1').hide();
	});
	$('#genresShowing').on('click',function() {
		$('#genre-window1').show();
	});
</script>