config/routes.rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  # アドレス帳用ルーティング
  patch '/end_user' => 'end_users#update'

  resources :addresses, only: [:index, :create, :edit, :update, :destroy]
  # カートアイテム用index
  # get '/cart_items' => 'cart_items#index'
  # カートアイテム用ルーティング
  resources :cart_items, only: [:index, :create, :update, :destroy]
  # カートアイテム全削除用
  delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
  # エンドユーザログイン管理ルーティング
  devise_for :end_users
  # エンドユーザ用ルーティング
  resource :end_users, only: [:show, :update]
  get '/end_users/editing' => 'end_users#edit'
  # 退会確認ページ用
  get '/end_users/withdraw' => 'end_users#withdraw'
  # アバウトページ用
  get '/homes/about' => 'homes#about'
  # トップページ用
  root to: 'homes#top'
  # 商品用ルーティング
  resources :items, only: [:index, :show]
  # 注文用ルーティング
  resources :orders, only: [:new, :create, :index, :show]
  # 購入確認ページ用
  get '/orders/confirm' => 'orders#confirm'
  # 購入完了ページ用
  get '/orders/thanks' => 'orders#thanks'
  ##エンドユーザ用ルーティング############################################
  resource :end_users, only: [:show, :edit, :update]

  ##管理ユーザ用ルーティング#############################################
  # 管理ユーザユーザログイン管理ルーティング
  devise_for :admin_users
  namespace :admin do
    # エンドユーザ用ルーティング
    resources :end_users, only: [:index, :show, :edit, :update]
    # ジャンル用ルーティング
    resources :genres, except: [:new, :show]
    # 商品用ルーティング
    resources :items, except: [:destroy]
    # 注文用ルーティング
    resources :orders, only: [:index, :show]
    # 注文ステータス更新用ルーティング
    patch '/orders/:id' => 'orders#update_order_status'
    # 製作ステータス更新用ルーティング
    put '/orders/:id' => 'orders#update_making_status'
  end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :end_user
  belongs_to :item
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  before_action :authenticate_end_user!
  include ApplicationHelper
  def create
    # カートに入れるアイテムの情報取得
    cart_item = CartItem.new( cart_item_params )
    # アイテムを入れたユーザの関連付け
    cart_item.end_user_id = current_end_user.id
    # カートへアイテム保存
    cart_item.save
    flash[:success] = "カート内に商品が追加されました。"
    # カート画面へ遷移
    redirect_to cart_items_path
  end

  def index
    # ログインユーザの全カートアイテム情報を取得
    @cart_items = current_end_user.cart_items
    # 先に商品合計額を算出
    @total_price = @cart_items.map{ | cart_item | subtotal( cart_item.item.listed_price, cart_item.amount, false ) }.sum
  end


  def update
    # 更新するカートアイテム情報を取得
    cart_item = CartItem.find( params[:id] )
    # 更新処理
    cart_item.update( cart_item_params )
    # カート画面へ遷移
    redirect_to cart_items_path
  end

  def destroy
    # ログに取得したidを出力
    logger.debug(params[:id])
    # ログにidの型を出力
    logger.debug(params[:id].class)
    if params[:id]=='destroy_all' then
      # ログに destroy_allの実行を出力
      logger.debug('performed: destroy_all')
      #  destroy_all実行
      destroy_all
      flash[:success] = "カート内アイテムを全て削除しました。"
    else
      # ログに 1個のカートアイテムを削除したことを出力
      logger.debug('performed: destroy')
      # 削除するカートアイテム情報を取得
      cart_item = CartItem.find( params[:id] )
      # 対象のカートアイテムを削除
      cart_item.destroy
      flash[:success] = "カート内アイテムを1件削除しました。"
    end
    # カート画面へ遷移
    redirect_to cart_items_path
  end

  private
  # ログインユーザの全カートアイテム削除アクション
  def destroy_all
    # ログインユーザの全カートアイテム情報を取得
    cart_items = current_end_user.cart_items
    # カートアイテムが存在するか判定
    if cart_items.nil? then
      # ない場合
      # flash[ :caution ] = "カートに商品がないため、削除できませんでした。"
    else
      # １個以上ある場合 => 全部削除
      cart_items.map(&:destroy)
      # flash[ :success ] = "削除が完了しました。"
    end
    # カート画面へ遷移はdestroyにて定義されている
  end

  def cart_item_params
    params.require( :cart_item ).permit( :end_user_id, :item_id, :amount )
  end
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/views/cart_items/index.html.erb
<body>
  <div class="container">
    <h3><strong>ショッピングカート</strong></h3>
      <!-- カートアイテム全項目の削除-->
      <%= link_to 'カートを空にする', cart_items_destroy_all_path, method: :delete, 'data-confirm' => '本当に削除しますか？', class: "btn btn-danger" %>
      <!-- 本当はグリッドシステムで揃えたい<div class="col-xs-12"> 磯辺-->
      <table class="cart-items">
        <tr class="cart-items-heading">
          <th width="300">商品名</th>
          <th>単価（税込）</th>
          <th width="200" >数量</th>
          <th width="120">小計</th>
          <th width="100"></th>
        </tr>
        <% @cart_items.each do |cart_item| %>
          <tr>
            <td>
              <!--商品イメージ-->
              <%= attachment_image_tag cart_item.item, :image, size:'70x70', format: 'jpeg', fallback: 'no_image.jpg', size:'70x70' %>
              <!--商品名-->
              <%= cart_item.item.name %>
            </td>
            <td class='pay-detail'>
              <!-- 単価（税込）-->
              <!--subtotal( 税抜き価格, 個数 ) => 小計（税込）を計算-->
              <%= subtotal( cart_item.item.listed_price, 1 ) %> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            </td>
            <td class="array-center">
              <!-- 数量-->
              <%= form_for( cart_item, url: cart_item_path( cart_item ) ) do | c | %>
              <%= c.number_field :amount, min:1 , style:'width: 50%;'%>
              <%= c.submit '変更', class: "btn btn-primary" %>
              <% end %>
            </td>
            <td class='pay-detail'>
              <!-- 小計-->
              <!--subtotal( 税抜き価格, 個数 ) => 小計（税込）を計算-->
              <%= subtotal( cart_item.item.listed_price, cart_item.amount ) %>
            </td>
            <td class="array-center">
              <!-- カートアイテム１項目の削除-->
              <%= link_to '削除する', cart_item_path( cart_item ), method: :delete, 'data-confirm' => "#{cart_item.item.name}をカートから削除しますか？", class: " btn btn-danger" %>
            </td>
          </tr>
        <% end %>
      </table>
    <!-- col-xs-12の閉じタグ</div> 磯辺-->

      <div class="row">
        <div class="col-xs-1 btn-shopping">
            <%= link_to '買い物を続ける', root_path, class: "btn btn-primary" %>
        </div>
        <!-- 横並び中央余白分col -->
        <div class="col-xs-5">
        </div>
        <table class="col-xs-3">
          <!-- <table> -->
            <tr>
              <td class="total-price">合計金額</td>
              <td><%= number_separation( @total_price ) %></td>
            </tr>
          </table>

       </div>
        <!-- 画面右の余白分 -->
        <%= link_to '情報入力に進む', new_order_path, class: "btn btn-primary" %>

  </div>
</body>