config/routes.rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  # アドレス帳用ルーティング
  patch '/end_user' => 'end_users#update'

  resources :addresses, only: [:index, :create, :edit, :update, :destroy]
  # カートアイテム用index
  # get '/cart_items' => 'cart_items#index'
  # カートアイテム用ルーティング
  resources :cart_items, only: [:index, :create, :update, :destroy]
  # カートアイテム全削除用
  delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
  # エンドユーザログイン管理ルーティング
  devise_for :end_users
  # エンドユーザ用ルーティング
  resource :end_users, only: [:show, :update]
  get '/end_users/editing' => 'end_users#edit'
  # 退会確認ページ用
  get '/end_users/withdraw' => 'end_users#withdraw'
  # アバウトページ用
  get '/homes/about' => 'homes#about'
  # トップページ用
  root to: 'homes#top'
  # 商品用ルーティング
  resources :items, only: [:index, :show]
  # 注文用ルーティング
  resources :orders, only: [:new, :create, :index, :show]
  # 購入確認ページ用
  get '/orders/confirm' => 'orders#confirm'
  # 購入完了ページ用
  get '/orders/thanks' => 'orders#thanks'
  ##エンドユーザ用ルーティング############################################
  resource :end_users, only: [:show, :edit, :update]

  ##管理ユーザ用ルーティング#############################################
  # 管理ユーザユーザログイン管理ルーティング
  devise_for :admin_users
  namespace :admin do
    # エンドユーザ用ルーティング
    resources :end_users, only: [:index, :show, :edit, :update]
    # ジャンル用ルーティング
    resources :genres, except: [:new, :show]
    # 商品用ルーティング
    resources :items, except: [:destroy]
    # 注文用ルーティング
    resources :orders, only: [:index, :show]
    # 注文ステータス更新用ルーティング
    patch '/orders/:id' => 'orders#update_order_status'
    # 製作ステータス更新用ルーティング
    put '/orders/:id' => 'orders#update_making_status'
  end
end

app/models/end_user.rb
class EndUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :cart_items
  has_many :orders
  has_many :addresses
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :authentication_keys => [ :email, :is_deleted ]
  columns = %w? first_name last_name first_name_kana last_name_kana address phone_number email ?
  columns.each do |column|
    eval( %?validates :#{column}, presence: true? )
  end
  validates :postal_code, presence: true, format: { with: /\A\d{7}\z/, message: "7桁の数字で入力されていません" }
end

app/controllers/admin/end_users_controller.rb
class Admin::EndUsersController < ApplicationController
	before_action :authenticate_admin_user!
	def index
		@users = EndUser.all
	end

	def show
		@end_user = EndUser.find(params[:id])
	end

	def edit
		@end_user = EndUser.find(params[:id])
	end

	def update
		# 編集されるユーザをピックアップ
		end_user = EndUser.find(params[:id])
		# アップデート
		end_user.update( admin_end_user_params )
		# フラッシュメッセージ
		flash[:success] = '会員情報を更新しました。'
		# 該当ユーザのshowページへ遷移
		redirect_to admin_end_user_path( end_user.id )
	end

	private
	def admin_end_user_params
		# パラメータの取得
    params.require( :end_user ).permit( :first_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :address, :phone_number, :email, :is_deleted )
  end
end

app/controllers/end_users_controller.rb
class EndUsersController < ApplicationController
  before_action :authenticate_end_user!

  def edit
    # なし
  end

  def update
    # ログインユーザ情報取得
    end_user = EndUser.find( current_end_user.id )
    # ユーザ情報更新
    end_user.update( end_user_params )
    flash[:success] = "ユーザー更新が正常に完了しました。"
    # ユーザが退会状態に変化した場合の処理
    if end_user.is_deleted then
      # logger.debug 'ログアウト処理実行'
      # ログアウト処理
      sign_out end_user

      flash[:success] = "退会処理が正常に完了しました。"
      redirect_to root_path
    else
      # ログインユーザ詳細画面へ遷移
    redirect_to end_users_path
    end
  end

  def show
    # なし
  end

  private
  def end_user_params
    params.require( :end_user ).permit( :first_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :address, :phone_number, :email, :is_deleted )
  end

end

app/helpers/end_users_helper.rb
module EndUsersHelper
end

app/views/end_users/edit.html.erb
<div class="container">
    <h2><strong>登録情報編集</strong></h2>
      <%= link_to '退会する', end_users_withdraw_path, class: "btn btn-danger" %>
      <%= form_for( current_end_user, url: end_user_path ) do | f | %>

  <table>
    <tr>
      <th>氏名</th>
      <td>
        <!--苗字-->
        <%= f.text_field :last_name, placeholder:'福澤' %>
        <!--名前-->
        <%= f.text_field :first_name, placeholder:'諭吉' %>
      </td>
    </tr>
    <tr>
      <th>カナ</th>
      <td>
        <!--苗字-->
        <%= f.text_field :last_name_kana, placeholder:'フクザワ' %>
        <!--名前-->
        <%= f.text_field :first_name_kana, placeholder:'ユキチ' %>
      </td>
    </tr>
    <tr>
      <th>郵便番号</th>
      <td><%= f.text_field :postal_code, placeholder:'1002100' %></td>
    </tr>
    <tr>
      <th>住所</th>
      <td><%= f.text_field :address, placeholder:'東京都小笠原村沖ノ鳥島1番地' %></td>
    </tr>
    <tr>
      <th>電話番号</th>
      <td><%= f.text_field :phone_number, placeholder:'0455034000' %></td>
    </tr>
    <tr>
      <th>メールアドレス</th>
      <td><%= f.text_field :email, placeholder:'end_user@example.com' %></td>
    </tr>
  </table>
  <%= f.submit '編集内容を保存する', class: "btn btn-primary col-xs-2" %>
  <% end %>
</div>

app/views/end_users/show.html.erb
<div class="container">
    <h3>マイページ</h3>
    <h3><strong>登録情報</strong></h3>
      <%= link_to '編集する', '/end_users/editing', class: "btn btn-primary" %>
      <%= link_to 'パスワードを変更する', edit_end_users_path , class: "btn btn-primary" %>

      <table class="my-profile">
        <tr>
          <th>氏名</th>
          <td>
            <!--苗字-->
            <%= current_end_user.last_name %>
            <!--名前-->
            <%= current_end_user.first_name %>
          </td>
        </tr>
        <tr>
          <th>カナ</th>
          <td>
            <!--苗字-->
            <%= current_end_user.last_name_kana %>
            <!--名前-->
            <%= current_end_user.first_name_kana %>
          </td>
        </tr>
        <tr>
          <th>郵便番号</th>
          <td><%= current_end_user.postal_code %></td>
        </tr>
        <tr>
          <th>住所</th>
          <td><%= current_end_user.address %></td>
        </tr>
        <tr>
          <th>電話番号</th>
          <td><%= current_end_user.phone_number %></td>
        </tr>
        <tr>
          <th>メールアドレス</th>
          <td><%= current_end_user.email %></td>
        </tr>
      </table><br>

    <strong>配送先　<%= link_to '一覧を見る', addresses_path, class: "btn btn-primary" %></strong><br>
    <strong>注文履歴<%= link_to '一覧を見る', orders_path, class: "btn btn-primary" %></strong>
  </div>
</div>

app/views/end_users/withdraw.html.erb

<div class="container withdraw-text">
	<h2>本当に退会しますか？</h2><br />
	<p>退会すると、会員登録情報や<br />
		これまでの購入履歴が閲覧できなくなります。<br />
		退会する場合は、「退会する」をクリックしてください。</p>

		<div style="display:inline-flex">
			<%= link_to "退会しない", end_users_path, class: "btn btn-primary" %>

			<%= form_for(current_end_user, url: end_user_path) do | f | %>
			<%= f.hidden_field :is_deleted, value:true %>
			<%= f.submit "退会する", class: "btn btn-danger" %>
			<% end %>
		</div>

</div>