config/routes.rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  # アドレス帳用ルーティング
  patch '/end_user' => 'end_users#update'

  resources :addresses, only: [:index, :create, :edit, :update, :destroy]
  # カートアイテム用index
  # get '/cart_items' => 'cart_items#index'
  # カートアイテム用ルーティング
  resources :cart_items, only: [:index, :create, :update, :destroy]
  # カートアイテム全削除用
  delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
  # エンドユーザログイン管理ルーティング
  devise_for :end_users
  # エンドユーザ用ルーティング
  resource :end_users, only: [:show, :update]
  get '/end_users/editing' => 'end_users#edit'
  # 退会確認ページ用
  get '/end_users/withdraw' => 'end_users#withdraw'
  # アバウトページ用
  get '/homes/about' => 'homes#about'
  # トップページ用
  root to: 'homes#top'
  # 商品用ルーティング
  resources :items, only: [:index, :show]
  # 注文用ルーティング
  resources :orders, only: [:new, :create, :index, :show]
  # 購入確認ページ用
  get '/orders/confirm' => 'orders#confirm'
  # 購入完了ページ用
  get '/orders/thanks' => 'orders#thanks'
  ##エンドユーザ用ルーティング############################################
  resource :end_users, only: [:show, :edit, :update]

  ##管理ユーザ用ルーティング#############################################
  # 管理ユーザユーザログイン管理ルーティング
  devise_for :admin_users
  namespace :admin do
    # エンドユーザ用ルーティング
    resources :end_users, only: [:index, :show, :edit, :update]
    # ジャンル用ルーティング
    resources :genres, except: [:new, :show]
    # 商品用ルーティング
    resources :items, except: [:destroy]
    # 注文用ルーティング
    resources :orders, only: [:index, :show]
    # 注文ステータス更新用ルーティング
    patch '/orders/:id' => 'orders#update_order_status'
    # 製作ステータス更新用ルーティング
    put '/orders/:id' => 'orders#update_making_status'
  end
end

app/views/layouts/_show_errors_index.html.erb
<div class="container">
  <div class="row">
    <!--errors_message-->
    <div class="col-xs-offset-2 col-xs-8 col-xs-offset-2">
      <h2><%= unit.errors.count  %>件のエラーが発生しました。</h2>
      <ul>
        <% unit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
      <!--error_message-->
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ながのCAKE</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<header class="navbar navbar-inverse">
  <nav class="navbar-left">
    <%= link_to root_path do %>
    <%= image_tag 'ながのCAKE.png' %>
    <% end %>
  </nav>

  <nav>
    <ul class="nav navbar-nav navbar-right">
      <!-- admin_userの場合 -->
      <% if admin_user_signed_in? %>
      <li>
        <%= link_to "商品一覧", admin_items_path %>
      </li>
      <li>
        <%= link_to "会員一覧", admin_end_users_path %>
      </li>
      <li>
        <%= link_to "注文履歴一覧", admin_orders_path %>
      </li>
      <li>
        <%= link_to "ジャンル管理", admin_genres_path %>
      </li>
      <li>
        <%= link_to "ログアウト", destroy_admin_user_session_path, method: :delete  %>
      </li>
      <!-- end_userの場合 -->
      <% elsif end_user_signed_in? %>
      <li>
        <%= link_to '#', style: 'color: white;' do %>
          ログインユーザ：<webcamp style='color: lightgreen;'><%= "#{current_end_user.last_name} #{current_end_user.first_name}" %></webcamp> 様
          <% end %>
      </li>
      <li>
        <%= link_to "Top", root_path %>
      </li>
      <li>
        <%= link_to "About", homes_about_path %>
      </li>
      <li>
        <%= link_to "My page", end_user_registration_path %>
      </li>
      <li>
        <%= link_to "Log out", destroy_end_user_session_path, method: :delete  %>
      </li>
      <li>
        <% cart_item_count = current_end_user.cart_items.map{ |i| i.amount }.sum  %>
        <%= link_to cart_items_path  do %>
        <span class="glyphicon glyphicon-shopping-cart" style='font-size: 50px;'><b><%= cart_item_count  %></b></span>
        <% end %>
      </li>
      <!-- どちらもlog inしていない場合 -->
      <% else %>
      <li>
        <%= link_to "About", homes_about_path %>
      </li>
      <li>
        <%= link_to "Sign up", new_end_user_registration_path %>
      </li>
      <li>
        <%= link_to "Log in", new_end_user_session_path %>
      </li>
      <% end %>
      <li>
        <%= form_for( Genre.new, url: items_path, method: :get ) do | f | %>
        <%= f.text_field :name, style: 'border: none; color: gray; margin-left: 8px;', placeholder: "フリーワードを入力" %>
        <%= f.submit '検索', class: 'btn btn-default', style: 'border: none; color: black;' %>
        <% end %>
      </li>
    </ul>
  </nav>
</header>

<body>
  <div class="container flash-message">
    <% if flash.any? then %>
    <!-- deviceのflashメッセージが出ないようにするため↓↓ -->
    <% flash.each do |key, value| %>
    <% if key != 'notice' then %>
    <%= value %><br>
    <% end %>
    <% end %>
    <% end %>
  </div>

  <%= yield %>

</body>


   <footer>
   </footer>
   <script>
     $(function(){
       $('b').css({
         'bottom': '5px',
         'right': '<%= 22 - 5*cart_item_count.to_s.length %>px'
       });
     });
   </script>
</html>